### ISSUE TITLE
Plate Kinetics Issue with certain files

### ISSUE THREAD

**Issue by nathanw23** [nathanw23/Analysis-Tools#1]
To reproduce

plate_kinetics --data_file "plate_kinetics_2.cav" --labels "1,2,3,4,5,6"

Error

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script

    exec(code, module.__dict__)

  File "/app/analysis-tools/Streamlit-App/app.py", line 55, in <module>

    df = interpret_plate_kinetics(data_file, labels)

  File "/app/analysis-tools/platereader/kinetics.py", line 36, in interpret_plate_kinetics

    df2 = pd.melt(df, id_vars=['Unnamed: 0', 'Unnamed: 2'], var_name='Timepoint',

  File "/home/appuser/venv/lib/python3.8/site-packages/pandas/core/reshape/melt.py", line 77, in melt

    raise KeyError(

**Comment by mattaq31** [comment]
Issue was due to you not putting in a group name.  Now fixed to deal with this issue if it happens :)
